name: Backend CD Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        type: string
      microservices:
        description: "List of microservices to deploy"
        required: true
        type: string

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          for SERVICE in $(echo "${{ inputs.microservices }}" | tr ',' '\n'); do
            # Generar etiqueta con la rama y el commit
            TAG=${{ inputs.branch }}-${{ github.sha }}
            echo "Building and pushing image for $SERVICE with tag $TAG"
            
            # Construir y etiquetar la imagen
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE:$TAG $SERVICE
            
            # Subir la imagen etiquetada con la rama y el commit
            docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE:$TAG
          done
