name: CD for Multiple Microservices

on:
  workflow_call:
    inputs:
      microservices:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "master"
    secrets:
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build and Push Docker Images
        run: |
          for SERVICE in $(echo "${{ inputs.microservices }}" | tr ',' '\n'); do
            # Generar etiqueta con la rama y el commit
            TAG=${{ inputs.branch }}-${{ github.sha }}
            echo "Building and pushing image for $SERVICE with tag $TAG"
            
            # Construir y etiquetar la imagen
            docker build -t ${{ secrets.docker_username }}/$SERVICE:$TAG $SERVICE
            
            # Subir la imagen etiquetada con la rama y el commit
            docker push ${{ secrets.docker_username }}/$SERVICE:$TAG
          done
