name: CD for Multiple Microservices

on:
  workflow_call:
    inputs:
      microservices:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "master"
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: List all files and directories
        run: |
          echo "Listing all files and directories in the workspace:"
          ls -laR

      - name: Validate Docker Context
        run: |
          for SERVICE in $(echo "${{ inputs.microservices }}" | tr ',' '\n'); do
            CONTEXT="obligatorio-devops-agustin/backend-services/$SERVICE"
            if [ ! -d "$CONTEXT" ]; then
              echo "Error: Directory $CONTEXT does not exist"
              exit 1
            fi
            if [ ! -f "$CONTEXT/Dockerfile" ]; then
              echo "Error: Dockerfile not found in $CONTEXT"
              exit 1
            fi
          done
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build and Push Docker Images
        run: |
          for SERVICE in $(echo "${{ inputs.microservices }}" | tr ',' '\n'); do
            echo "Building and pushing image for $SERVICE"
            docker build -t ${{ secrets.docker_username }}/$SERVICE:${{ github.sha }} obligatorio-devops-agustin/backend-services/$SERVICE
            docker push ${{ secrets.docker_username }}/$SERVICE:${{ github.sha }}
          done
