name: CD for Multiple Microservices

on:
  workflow_call:
    inputs:
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string
      microservices:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: "master"

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.docker_username }}
          password: ${{ inputs.docker_password }}

      - name: Build and Push Docker Images
        run: |
          for SERVICE in $(echo "${{ inputs.microservices }}" | tr ',' '\n'); do
            echo "Building and pushing image for $SERVICE"
            docker build -t ${{ inputs.docker_username }}/$SERVICE:${{ github.sha }} obligatorio-devops-agustin/backend-services/$SERVICE
            docker push ${{ inputs.docker_username }}/$SERVICE:${{ github.sha }}
          done
