name: Reusable Frontend Sync Workflow

on:
  workflow_call:
    inputs:
      s3_bucket:
        required: true
        type: string
      aws_access_key:
        required: true
        type: string
      aws_secret_key:
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync Build to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_key }}
        run: |
          aws s3 sync build/ s3://${{ inputs.s3_bucket }} --delete
